name: AI Code Reviewer

on:
  pull_request:
    types:
      - opened
      - synchronize
permissions: write-all
jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: AI Code Reviewer
        uses: ysh4296/ai-code-reviewer@main
        with:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_API_MODEL: "gpt-4o-mini" # Optional: defaults to "gpt-4o-mini"
          COMMENT_LANGUAGE: "en-US" # Optional: defaults to "en-US"
          REVIEW_MAX_COMMENTS: 5 # Optional: defaults to 10
          REVIEW_PROJECT_CONTEXT: "PHP 8.3 + Laravel 10 + PHPUnit 7." # Optional
          exclude: "**/*.json, **/*.md" # Optional: exclude patterns separated by commas
